# ============================================================
#  FeatureBox - Default Configuration
# ============================================================

# --- Custom Items & Features ---------------------------------
# Section for custom items and gameplay features.

ender_wand:
  distance: 100       # Maximum teleportation distance for Ender Wand (in blocks)
  max_usage: 50       # Number of uses before the Ender Wand breaks
  enabled: true       # Enable/disable the Ender Wand feature

riptide:
  enabled: true       # Enable/disable custom Riptide boost (Poseidon trident)
  speed: 1            # Base speed multiplier for Riptide boost

# --- Custom Mobs ---------------------------------------------
# Section for custom mobs that replace vanilla entities.

mobs:
  enabled: true       # Enable/disable custom mob spawning
  list: []            # List of custom mobs (see examples below)
    # Example custom mob configurations:
    # - name: Arthessia # Custom mob name (displayed in-game)
    #   replaceEntity: minecraft:skeleton # Entity type to replace
    #   stuff:           # Equipment for the custom mob
    #     - material: LEATHER_BOOTS
    #       enchants:
    #         - name: minecraft:protection
    #           level: 1
    #     - material: BOW
    #       enchants:
    #         - name: minecraft:flame
    #           level: 1
    #   spawnChance: 25 # Chance (%) for this mob to spawn instead of the vanilla entity

    # - name: Dead Matthieu
    #   replaceEntity: minecraft:skeleton
    #   stuff:
    #     - material: NETHERITE_BOOTS
    #       enchants:
    #         - name: minecraft:protection
    #           level: 4
    #         - name: minecraft:mending
    #           level: 1
    #     - material: BOW
    #       enchants:
    #         - name: minecraft:flame
    #           level: 1
    #         - name: minecraft:mending
    #           level: 1
    #         - name: minecraft:infinity
    #           level: 1
    #   spawnChance: 1

# --- Custom Recipes ------------------------------------------
# Section for custom crafting recipes and their effects.

recipes: []          # List of custom recipes (see examples below)
  # Example custom recipe configurations:
  # Each recipe must have a unique key (e.g., fish_soup, magic_cookie)
  # fish_soup:
  #   icon: MUSHROOM_STEW         # Item icon for the recipe result
  #   name: "§7Une soupe délicieuse" # Display name for the crafted item
  #   lore:                       # Lore (description) lines for the item
  #     - "§7→ Permet de respirer sous l'eau pendant 10 min"
  #   shape:                      # Crafting grid shape (3x3, use / for empty slots)
  #     - "AAA"
  #     - "/V/"
  #   ingredients:                # Ingredient mapping for each shortcut letter
  #     - shortcut: A
  #       key: COD
  #     - shortcut: V
  #       key: BOWL
  #   effects:                    # Effects applied when consuming the item
  #     - key: WATER_BREATHING
  #       duration: 600           # Duration in seconds
  #       amplifier: 0
  #   glow: true                  # Whether the item glows (enchanted effect)

  # magic_cookie:
  #   icon: COOKIE
  #   name: "§dMagic Cookie"
  #   lore:
  #     - "§7Un biscuit mystérieux…"
  #     - "§7→ Donne de la vitesse et régénère la vie"
  #   shape:
  #     - "SSS"
  #     - "SCS"
  #     - "SSS"
  #   ingredients:
  #     - shortcut: S
  #       key: SUGAR
  #     - shortcut: C
  #       key: COOKIE
  #   effects:
  #     - key: SPEED
  #       duration: 300           # Duration in seconds
  #       amplifier: 1
  #     - key: REGENERATION
  #       duration: 60            # Duration in seconds
  #       amplifier: 0
  #   glow: true

# --- Unused / Experimental Entities --------------------------
# Section for enabling/disabling and configuring unused mobs.

unused:
  rabbit:
    spawn:
      enabled: true             # Enable/disable killer rabbit spawn
      chance: 10                # Chance (%) for killer rabbit to spawn

  zombiehorse:
    spawn:
      enabled: true             # Enable/disable zombie horse spawn
      chance: 15                # Chance (%) for zombie horse to spawn
      limit: 3                  # Maximum number of zombie horses per chunk (-1 for unlimited)

  illusioner:
    spawn:
      enabled: true             # Enable/disable illusioner spawn
      chance: 5                 # Chance (%) for illusioner to spawn

# --- Common Features -----------------------------------------
# Section for miscellaneous features (death messages, location, totem behavior).

common:
  name:
    death:
      enabled: true             # Enable/disable custom death message for mobs
      template: "§cAssassin de {victim}" # Template for mob name after killing a player
  location:
    death:
      enabled: true             # Enable/disable sending location to player on death
  totem:
    death:
      inventory:
        enabled: true           # Enable/disable totem saving effect from inventory/bundle

# --- Teleport Stones -----------------------------------------
# Section for configuring teleport stones (lightning rods) and their behavior.
teleport:
  item_name: Teleportation Stone # Name of the teleportation item
  enabled: true         # Global toggle: enable/disable the teleport system
  distance: 200         # Minimum distance (in blocks) required between two teleport stones
  lightning: false      # Global setting: should lightning effects be used on teleport (can be overridden per stone)

  sound:
    discovery: true                     # Only allow players to see stones they have already discovered
    teleport: block.end_portal.spawn    # Default sound played when teleporting
    ambient: ambient.basalt_deltas.mood # Default ambient sound around teleport stones
    volume: 1.0                         # Default sound volume
    pitch: 1.0                          # Default sound pitch
    delay: 10                           # Delay in seconds between ambient effects

  particle: end_rod    # Default particle effect around teleport stones

  # -----------------------------
  # User profiles (optional)
  # If profile exists, its values are copied when the player creates a new stone
  # If not, nothing is copied (stone keeps defaults)
  # -----------------------------
  profiles: []         # List of user profiles (see example below)
    # Example profile configuration:
    # Each profile must have a unique key (e.g., PlayerName)
    # PlayerName:
    #   lightning: false                     # Disable lightning flashes
    #   ambient: music_disc.chirp            # Custom ambient sound
    #   teleport: block.end_portal.spawn     # Custom teleportation sound
    #   particle: flame                      # Custom particle effect

  stones: []          # List of teleport stones (see example below)
    # You can let it empty initially; stones will be added as players create them.
    # Each stone must have a unique key (e.g., SPAWN, HOME, etc.)
    # SPAWN:                                # Unique identifier for the stone
    #   name: §aSpawn Stone                 # Display name (can use color codes §)
    #   players: []                         # List of UUIDs of players who have discovered this stone
    #   creator: <UUID>                     # UUID of the player who created the stone
    #   world: world                        # World name where the stone is placed
    #   material: STONE                     # Item used as the clickable icon in the teleport menu
    #   x: 0                                # Block X coordinate of the lightning rod
    #   y: 65                               # Block Y coordinate of the lightning rod
    #   z: 0                                # Block Z coordinate of the lightning rod

    #   # Per-stone customization (optional, overrides global defaults):
    #   lightning: true                     # Should lightning strike effect be shown when teleporting to/from this stone
    #   particle: portal                    # Custom particle effect for this stone
    #   sound:
    #     teleport: entity.enderman.teleport # Custom teleport sound for this stone
    #     ambient: block.beacon.ambient      # Custom ambient looping sound for this stone
    #     volume: 1.5                        # Custom sound volume
    #     pitch: 0.8                         # Custom sound pitch
