main: arthessia.featurebox.Plugin
name: featurebox
authors: [Arthessia]
version: 1.0.0.8
api-version: "1.21"

commands:
    featurebox:
        description: "Reload featurebox plugin"
        usage: "/featurebox <reload>"
        permission: arthessia.featurebox.reload
    riptidetoggle:
        description: "Toggle to enable or disable riptide feature"
        usage: "/riptidetoggle"
        permission: arthessia.featurebox.riptidetoggle
    riptideforce:
        description: "Command to set a new force for riptide"
        usage: "/riptideforce <number>"
        permission: arthessia.featurebox.riptideforce
    unusedtoggle:
        description: "Toggle to enable or disable an unused entity"
        usage: "/unusedtoggle <rabbit | illusioner | zombiehorse>"
        permission: arthessia.featurebox.unusedtoggle
    unusedchance:
        description: "Command to set the spawn chance of an unused entity"
        usage: "/unusedchance <rabbit | illusioner | zombiehorse> <percent>"
        permission: arthessia.featurebox.unusedchance
    unusedlimit:
        description: "Command to set the spawn limit of an unused entity (-1 for no limit)"
        usage: "/unusedlimit <zombiehorse> <limit (-1 for no limit)>"
        permission: arthessia.featurebox.unusedlimit
    ondeathtoggle:
        description: "Toggle to enable or disable the location sent to player on death"
        usage: "/ondeathtoggle"
        permission: arthessia.featurebox.ondeathtoggle
    custommobtoggle:
        description: "Toggle to enable or disable the custom mob feature"
        usage: "/custommobtoggle"
        permission: arthessia.featurebox.custommobtoggle
    findcustommob:
        description: "Find a custom entity"
        usage: "/findcustommob <custom name>"
        permission: arthessia.featurebox.findcustommob
    undyingtoggle:
        description: "Toggle to enable or disable the undying feature."
        usage: "/undyingtoggle"
        permission: arthessia.featurebox.undyingtoggle
    featureboxprofile:
        description: Main command for FeatureBox
        usage: /featureboxprofile <args>
        aliases: [fb]
